package com.example.pluslife.models.enum

enum class DadosSharedSecret {
    USUARIO_ID,
    USUARIO_NOME,
    USUARIO_EMAIL,
    USUARIO_NASCIMENTO,
    USUARIO_TIPO_SANGUINEO,
    USUARIO_LOGADO,
    ENDERECO_RUA,
    ENDERECO_BAIRRO,
    ENDERECO_NUMERO,
    ENDERECO_CIDADE,
    ENDERECO_ESTADO
}