package com.example.pluslife.models.enum

enum class UsuarioSharedSecret {
    USUARIO_ID,
    USUARIO_NOME,
    USUARIO_EMAIL,
    USUARIO_NASCIMENTO,
    USUARIO_TIPO_SANGUINEO,
    USUARIO_LOGADO,
    USUARIO_ENDERECO_RUA,
    USUARIO_ENDERECO_BAIRRO,
    USUARIO_ENDERECO_NUMERO,
    USUARIO_ENDERECO_CIDADE,
    USUARIO_ENDERECO_ESTADO
}